### ISSUE TITLE
wakepy crashes a program which has been built into an executable

### ISSUE THREAD

**Issue by AndyW118** [fohrloop/wakepy#49]
The following program (I used pyinstaller to make an executable) immediately crashes - see below.
```
from wakepy import keep
import time

with keep.running() as k:
    while True:
        time.sleep(10)
```
Stack backtrace:
D:\PyCharm Projects\keepAwake\dist>keepawake.exe
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "contextlib.py", line 117, in __enter__
  File "wakepy\keep.py", line 87, in running
  File "wakepy\keep.py", line 45, in _temporary_solution_for_using_old_functions_with_new_api
  File "wakepy\_deprecated\__init__.py", line 37, in get_function
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wakepy._deprecated._windows'
[12692] Failed to execute script 'main' due to unhandled exception!

**Comment by fohrloop** [comment]
As a quick comment, I would guess this is because there are dynamical imports in wakepy, and I guess the pyinstaller might not understand to include all the modules to the build. 

There probably is some option in pyinstaller which allows you to see which modules (.py files) it did include. Could you check which files were included?

**Comment by AndyW118** [comment]
Here's the result of a 'verbose' debug build.  Hope it helps.
[wakepyVerboseDump.txt](https://github.com/fohrloop/wakepy/files/12565424/wakepyVerboseDump.txt)

**Comment by fohrloop** [comment]
Thanks for the dump! Basically what it says is the same as in the original question:

```
ModuleNotFoundError: No module named 'wakepy._deprecated._windows'
```

What this means is that when you're bundling your python app into an executable with pyinstaller, pyinstaller has not included the file [wakepy._deprecated._windows.py](https://github.com/fohrloop/wakepy/blob/0.7.1/wakepy/_deprecated/_windows.py). The reason is that wakepy 0.7.1 detects your operating system and imports the correct module at run-time in [wakepy/_deprecated/\_\_init\_\_.py](https://github.com/fohrloop/wakepy/blob/0.7.1/wakepy/_deprecated/__init__.py) using the `importlib.import_module`. 

The pyinstaller documentation talks [here](https://pyinstaller.org/en/stable/operating-mode.html) about what kinds of modules pyinstaller can automatically detect. It mentions specifically that modules imported dynamically for example with `importlib.import_module` are not automatically detected by pyinstaller. 

I have no experience on pyinstaller so unfortunately I probably cannot help you further with that; I'm guessing this is more about your pyinstaller configuration than about wakepy. I would go first through the pyinstaller docs and make sure it includes all the modules for the used packages. In case of wakepy 0.7.1, you would need to include all the modules from `wakepy/_deprecated`.

**Comment by ElliotGarbus** [comment]
I frequently use pyinstaller but have not used it with wakepy.  To address these kinds of issue there are 2 fixes.

You can add the missing imports to the hidden_imports list (via spec file or command line), or you can simply do an explicit import of the module in your python code.  I usually just add the import explicitly in my main.py with a comment that it is for pyinstaller.

 

There is a discussion on this issue here: https://pyinstaller.org/en/stable/when-things-go-wrong.html?highlight=hidden#listing-hidden-imports

**Comment by fohrloop** [comment]
Nice to hear you found a solution!
